services:
  unclespace:
    build: .
    container_name: unclespace
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    env_file: .env
    networks:
      - proxy_network  # Общая сеть для Nginx

networks:
  proxy_network:
    external: true     # Создается отдельно для Nginx