version: '3.8'
services:
  web:
    build: .
    container_name: unclespace
    environment:
      - VIRTUAL_HOST=unclespace.ru
      - LETSENCRYPT_HOST=unclespace.ru
      - LETSENCRYPT_EMAIL=dmitrachkovivan@gmail.com
      - NODE_ENV=production
    expose:
      - "3000"
    restart: always
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
