name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo "${{ secrets.VPS_HOST }} ssh-ed25519 AAAAC3..." >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          ssh -i ~/.ssh/deploy_key \
              -o StrictHostKeyChecking=no \
              ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
              "echo 'SSH подключение успешно!'"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script_timeout: 15m
          script: |
            set -euxo pipefail
            echo "=== Начало деплоя ==="
            
            cd /var/www/unclespace || { echo "Ошибка: директория не найдена"; exit 1; }
            git config --global --add safe.directory /var/www/unclespace
            git reset --hard
            git pull origin main
            
            docker compose version
            docker compose down --remove-orphans
            docker compose build --no-cache --pull
            docker compose up -d --force-recreate
            
            echo "=== Деплой успешен ==="
            docker ps